openapi: 3.0.0
info:
  title: Expense Tracker Service API
  description: API for managing Expenses.
  version: "1.0"
paths:
  /health:
    get:
      summary: Health Check
      responses:
        '200':
          description: Uptime